---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.deployment.name }}
  labels:
    {{- include "master.labels.common" $ | nindent 4 }}
    {{- with $.Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # TODO:
  #  As of now, Axelix Master backend does not really support multiple replicas being deployed,
  #  nor it supports the HPA. The reason is the internal design of Axelix Master. We're gonna
  #  address that if we're going to see the need from the community.
  replicas: 1
  selector:
    matchLabels:
      {{- include "master.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "master.labels.common" $ | nindent 8 }}
        {{- with $.Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      securityContext:
        {{- toYaml $.Values.pod.securityContext | nindent 8 }}
      containers:
        - name: axelix-master
          image: "{{ $.Values.image.name }}:{{ $.Values.image.ref }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ $.Values.liveness.delay }}
            periodSeconds: {{ $.Values.liveness.period }}
            failureThreshold: {{ $.Values.liveness.failureThreshold }}
            timeoutSeconds: {{ $.Values.liveness.timeoutSeconds }}
            httpGet:
              path: /api/actuator/health/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: {{ $.Values.readiness.delay }}
            periodSeconds: {{ $.Values.readiness.period }}
            failureThreshold: {{ $.Values.readiness.failureThreshold }}
            timeoutSeconds: {{ $.Values.readiness.timeoutSeconds }}
            httpGet:
              path: /api/actuator/health/readiness
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- with $.Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with $.Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
