---
{{- with $.Values.backend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "master.backend.name" $ }}
  labels:
    {{- include "master.backend.labels" $ | nindent 4 }}
    {{- with .custom.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .custom.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "master.backend.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "master.backend.labels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "master.backend.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "master.backend.name" $ }}
          image: "{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .liveness.delay }}
            periodSeconds: {{ .liveness.period }}
            failureThreshold: {{ .liveness.failureThreshold }}
            timeoutSeconds: {{ .liveness.timeoutSeconds }}
            httpGet:
              path: /api/axelix/actuator/health/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .readiness.delay }}
            periodSeconds: {{ .readiness.period }}
            failureThreshold: {{ .liveness.failureThreshold }}
            timeoutSeconds: {{ .readiness.timeoutSeconds }}
            httpGet:
              path: /api/axelix/actuator/health/readiness
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
---
{{- with $.Values.frontend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "master.frontend.name" $ }}
  labels:
    {{- include "master.frontend.labels" $ | nindent 4 }}
    {{- with .custom.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .custom.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "master.frontend.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "master.frontend.labels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "master.frontend.serviceAccountName" $ }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "master.frontend.name" $ }}
          image: "{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .liveness.delay }}
            periodSeconds: {{ .liveness.period }}
            failureThreshold: {{ .liveness.failureThreshold }}
            timeoutSeconds: {{ .liveness.timeoutSeconds }}
            httpGet:
              path: /api/axelix/actuator/health/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .readiness.delay }}
            periodSeconds: {{ .readiness.period }}
            failureThreshold: {{ .liveness.failureThreshold }}
            timeoutSeconds: {{ .readiness.timeoutSeconds }}
            httpGet:
              path: /api/axelix/actuator/health/readiness
              port: http
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}