---
{{- if $.Values.backend.autoscaling.enabled }}
{{- with $.Values.backend }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "master.backend.name" $ }}
  labels:
    {{- include "master.backend.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "master.backend.name" $ }}
  minReplicas: {{ .autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.hpa.targetCPU }}
    {{- end }}
    {{- if .autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.hpa.targetMemory }}
    {{- end }}
{{- end }}
{{- end }}
---
{{- if $.Values.frontend.autoscaling.enabled }}
{{- with $.Values.frontend }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "master.frontend.name" $ }}
  labels:
    {{- include "master.frontend.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "master.frontend.name" $ }}
  minReplicas: {{ .autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.hpa.targetCPU }}
    {{- end }}
    {{- if .autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.hpa.targetMemory }}
    {{- end }}
{{- end }}
{{- end }}
