{{- if $.Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default $.Chart.Name $.Values.ingress.name }}
  namespace: {{ $.Values.ingress.default }}
  labels:
    {{- include "master.backend.labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $.Values.ingress.host | quote }}
      secretName: {{ $.Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ include "master.backend.name" $ }}
                port:
                  number: 8080
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: {{ include "master.frontend.name" $ }}
                port:
                  number: 80
            path: /
            pathType: Prefix
      {{- if $.Values.ingress.host }}
      host: {{ $.Values.ingress.host | quote }}
      {{- end }}
{{- end }}
