{{- if $.Values.rbac.autoCreateRole }}
{{- range $.Values.rbac.targetNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "master.labels.common" $ | nindent 4 }}
  name: {{ $.Values.serviceAccount.name }}-role
  namespace: {{ . }}
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "endpoints" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "master.labels.common" $ | nindent 4 }}
  name: {{ $.Values.serviceAccount.name }}-role-binding
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccount.name }}
    namespace: {{ $.Values.serviceAccount.namespace | default $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $.Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}